import { useMutation } from '@tanstack/react-query'
import { AnimatePresence, motion } from 'framer-motion'
import { Check, CheckCircle2, Loader2, Send, X, XCircle } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'

import { interviewApi } from '@/api/interview'
import { Button } from '@/components/ui/button'
import { getErrorMessage } from '@/lib/errors'
import { formatDateTime } from '@/lib/format'
import { cn } from '@/lib/utils'
import type { Evaluation } from '@/types'

interface HitlGateProps {
  evaluation: Evaluation
  onEvaluationChange: (evaluation: Evaluation) => void
}

const panelMotion = {
  initial: { opacity: 0, y: 4 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -4 },
  transition: { duration: 0.15, ease: 'easeOut' as const },
}

export function HitlGate({ evaluation, onEvaluationChange }: HitlGateProps) {
  const [inviteSentAt, setInviteSentAt] = useState<string | null>(null)

  const approve = useMutation({
    mutationFn: interviewApi.approve,
    onSuccess: (updated) => {
      onEvaluationChange({ ...evaluation, ...updated, status: 'APPROVED' })
      toast.success('Evaluation approved')
    },
    onError: (error) => toast.error('Could not approve', { description: getErrorMessage(error) }),
  })

  const reject = useMutation({
    mutationFn: interviewApi.reject,
    onSuccess: (updated) => {
      onEvaluationChange({ ...evaluation, ...updated, status: 'REJECTED' })
      toast.success('Evaluation rejected')
    },
    onError: (error) => toast.error('Could not reject', { description: getErrorMessage(error) }),
  })

  const invite = useMutation({
    mutationFn: interviewApi.sendInvite,
    onSuccess: (data) => {
      setInviteSentAt(data.sentAt || new Date().toISOString())
      toast.success('Interview invite sent')
    },
    onError: (error) => toast.error('Could not send invite', { description: getErrorMessage(error) }),
  })

  const deciding = approve.isPending || reject.isPending
  const status = evaluation.status
  const panelKey = status === 'APPROVED' && inviteSentAt ? 'sent' : status.toLowerCase()

  return (
    <section
      aria-labelledby="hitl-heading"
      className={cn(
        'rounded-lg border border-l-4 bg-card p-6',
        status === 'PENDING' && 'border-l-amber-500',
        status === 'APPROVED' && 'border-l-emerald-500',
        status === 'REJECTED' && 'border-l-rose-500'
      )}
    >
      <AnimatePresence mode="wait" initial={false}>
        {status === 'PENDING' && (
          <motion.div key={panelKey} {...panelMotion}>
            <h3 id="hitl-heading" className="text-sm font-medium">
              Human approval required
            </h3>
            <p className="mt-1 max-w-prose text-sm leading-6 text-muted-foreground">
              This recommendation is generated by AI. Review it carefully. Approve to unlock the
              interview invite action. Reject to close this evaluation.
            </p>
            <div className="mt-5 flex flex-col gap-2 sm:flex-row">
              <Button
                type="button"
                onClick={() => approve.mutate(evaluation.id)}
                disabled={deciding}
                className="bg-emerald-600 text-white hover:bg-emerald-700 focus-visible:ring-emerald-600 dark:bg-emerald-600 dark:hover:bg-emerald-500"
              >
                {approve.isPending ? (
                  <Loader2 className="animate-spin" aria-hidden="true" />
                ) : (
                  <Check aria-hidden="true" />
                )}
                Approve
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => reject.mutate(evaluation.id)}
                disabled={deciding}
                className="border-destructive/40 text-destructive hover:bg-destructive/10 hover:text-destructive"
              >
                {reject.isPending ? (
                  <Loader2 className="animate-spin" aria-hidden="true" />
                ) : (
                  <X aria-hidden="true" />
                )}
                Reject
              </Button>
            </div>
          </motion.div>
        )}

        {status === 'APPROVED' && !inviteSentAt && (
          <motion.div key={panelKey} {...panelMotion}>
            <h3
              id="hitl-heading"
              className="flex items-center gap-2 text-sm font-medium text-emerald-700 dark:text-emerald-300"
            >
              <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
              Evaluation approved
            </h3>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">
              You can now invite the candidate to the next interview stage.
            </p>
            <Button
              type="button"
              className="mt-5"
              onClick={() => invite.mutate(evaluation.id)}
              disabled={invite.isPending}
            >
              {invite.isPending ? (
                <Loader2 className="animate-spin" aria-hidden="true" />
              ) : (
                <Send aria-hidden="true" />
              )}
              Send interview invite
            </Button>
          </motion.div>
        )}

        {status === 'APPROVED' && inviteSentAt && (
          <motion.div key={panelKey} {...panelMotion}>
            <h3
              id="hitl-heading"
              className="flex items-center gap-2 text-sm font-medium text-emerald-700 dark:text-emerald-300"
            >
              <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
              Interview invite sent
            </h3>
            <p className="mt-1 text-sm text-muted-foreground tabular-nums">
              Sent {formatDateTime(inviteSentAt) ?? 'just now'}
            </p>
          </motion.div>
        )}

        {status === 'REJECTED' && (
          <motion.div key={panelKey} {...panelMotion}>
            <h3
              id="hitl-heading"
              className="flex items-center gap-2 text-sm font-medium text-rose-700 dark:text-rose-300"
            >
              <XCircle className="h-4 w-4" aria-hidden="true" />
              Evaluation rejected
            </h3>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">
              This evaluation is closed. No further actions are available.
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  )
}
