spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: placeholder_username
    password: placeholder_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.recruit: DEBUG
