CREATE DATABASE IF NOT EXISTS recruitdb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE recruitdb;

-- System users (HR staff and admins who log in to the platform)
CREATE TABLE users (
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role        ENUM('HR', 'ADMIN') NOT NULL,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- Job postings that candidates apply to
CREATE TABLE jobs (
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- Candidate profiles (one row per person)
CREATE TABLE candidates (
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- Uploaded resumes linking a candidate to a job they applied for
CREATE TABLE resumes (
    id           BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    candidate_id BIGINT       NOT NULL,
    job_id       BIGINT       NOT NULL,
    raw_text     LONGTEXT,
    file_path    VARCHAR(500),
    uploaded_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resumes_candidate FOREIGN KEY (candidate_id) REFERENCES candidates(id),
    CONSTRAINT fk_resumes_job       FOREIGN KEY (job_id)       REFERENCES jobs(id)
);

-- AI-generated evaluations reviewed by humans (HITL gate lives here via status column)
CREATE TABLE evaluations (
    id             BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    candidate_id   BIGINT        NOT NULL,
    job_id         BIGINT        NOT NULL,
    stage          ENUM('SCREENING', 'INTERVIEW') NOT NULL,
    match_score    DECIMAL(5,2),
    recommendation ENUM('HIRE', 'CONSIDER', 'REJECT'),
    rationale      TEXT,
    questions      LONGTEXT      COMMENT 'JSON array of interview questions generated by the AI agent',
    status         ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_evaluations_candidate FOREIGN KEY (candidate_id) REFERENCES candidates(id),
    CONSTRAINT fk_evaluations_job       FOREIGN KEY (job_id)       REFERENCES jobs(id)
);
